import Head from "next/head"
import { BsFillMoonStarsFiil } from "react-icons"


export default function Home() {


  return (
    <div>
      <Head>
        <title>Ceyhun Ozyilmaz Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <section className="min-h-screen">
          <nav>
            <h1>developedyed</h1>
            <ul>
              <li></li>
              <li><a href="#">Resume</a></li>
            </ul>
          </nav>
        </section>
      </main>
    </div >
  )
}